### ISSUE TITLE
System for adding publications to central database is located on the old website

### ISSUE THREAD

**Issue by rmward61** [EECi/home#12]
Should we still maintain a central database of publications or do we each do our own?  If we wish for a central database we need to decide where it should be located

**Comment by rmward61** [comment]
Imported previous bibbase file so that it can be added to here, rather than on the old website.

**Comment by anetobradley** [comment]
There are a few ways of doing this so might be worth discussing this over Zoom... it might be good if we could set this up to automatically update for everyone?

**Comment by mal84emma** [comment]
Documentation in docs/publications/readme.md updated to discuss options.
Combined bib file for the group has been updated.
