### ISSUE TITLE
September EECinsights

### ISSUE THREAD

**Issue by mal84emma** [EECi/home#14]
Max: academic visitors to group (include photos)

**Comment by mal84emma** [comment]
Hi Nik, should we push this back to the September issue and just shift the schedule by a month? I know everyone's got a lot on their plate atm. We could even make it a 'summer round-up' and publish it at the start of term in October?

**Comment by nikolas-makasis** [comment]
Hey Max! Thank you for the reminder. I will start putting this together and see what additional information other people have (I wasn't here for some of the visits I think). Summer round-up might be more appropriate I think but I'll bring it up tomorrow in the group meeting.
Hope your month off is going well!
