### ISSUE TITLE
image sizing

### ISSUE THREAD

**Issue by meljsingh** [EECi/home#7]
e.g. size Introduction header image so it's less long

**Comment by anetobradley** [comment]
I think this can be fixed by creating and apply a css class for this type of image (say we call it 'thumbnail' for the gallery of people)... I might have a crack at this.

**Comment by anetobradley** [comment]
So I've done a bit of fiddling with the main.scss file in assets/css to add an image class. Might and the gallery page now crops images to 200x220px but may need to review this.

**Comment by anetobradley** [comment]
This is now fixed for galleries and feature rows. But I suggest we use a different layout for what is currently the projects page and have some rules for gallery picture aspect ratio and banner image/project images.
